### PR TITLE
jcf / IT-academy / M-JC1-55-20 / Roman Honcharuk / task done 

### PR DESCRIPTION
**Pull request by RomaHoncharuk**
## Pull request state

Please indicate actual status for PR:
- [x] on review
- [ ] reviewed
- [ ] fixed
- [ ] on approve
- [ ] approved

### CODE REVIEW

**Comment by RomaHoncharuk** [comment]
jcf done

**Comment by RomaHoncharuk** [comment]
io done to))

**Review by rakovets — CHANGES_REQUESTED** [review]
PR title is wrong!

**Comment by rakovets** [comment]
I fixed PR title.

**Review by rakovets — COMMENTED** [review]
Well!
Reviewed in the lesson.

**Pull request closed without merging**
